# Numpy
It is a general purpose array processing package. It provides high performance multi dimensional array object and tools for working with these arrays. It is the fundamental package for scientific computing with Python

#### What is an array?
Data structure that stores values of same data type. While lists can store values of different data types, arrays can only contain values of same data type


### Python Lists
1) Element Overhead: Lists in Python store additional information about each element, such as its type and reference count. This overhead can be significant when dealing with a large number of elements.
2) Datatype: Lists can hold different data types, but this can decrease memory efficiency and slow numerical operations.
3) Memory Fragmentation: Lists may not store elements in contiguous memory locations, causing memory fragmentation and inefficiency.
4) Performance: Lists are not optimized for numerical computations and may have slower mathematical operations due to Python’s interpretation overhead. They are generally used as general-purpose data structures.
Functionality: Lists can store any data type, but lack specialized NumPy functions for numerical operations.

### Numpy Array
1) Homogeneous Data: NumPy arrays store elements of the same data type, making them more compact and memory-efficient than lists.
2) Fixed Data Type: NumPy arrays have a fixed data type, reducing memory overhead by eliminating the need to store type information for each element.
3) Contiguous Memory: NumPy arrays store elements in adjacent memory locations, reducing fragmentation and allowing for efficient access.
4) Array Metadata: NumPy arrays have extra metadata like shape, strides, and data type. However, this overhead is usually smaller than the per-element overhead in lists.
5) Performance: NumPy arrays are optimized for numerical computations, with efficient element-wise operations and mathematical functions. These operations are implemented in C, resulting in faster performance than equivalent operations on lists.


In [4]:
import numpy as np

In [5]:
list1 = [1,2,3,4,5]

arr = np.array(list1)

arr

array([1, 2, 3, 4, 5])

In [12]:
type(arr)

numpy.ndarray

In [13]:
arr.shape

(5,)

In [16]:
# Miltinested array

list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
list3 = [11,12,13,14,15]

arr = np.array([list1,list2,list3])

print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [17]:
arr.shape

(3, 5)

In [30]:
arr = arr.reshape(5,3)

arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [29]:
arr[2]

array([7, 8, 9])

In [31]:
arr[2][1]

8

In [33]:
arr[2,1] #arr[row,column]

8

In [35]:
arr[:,:] #Will retrieve whole data

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [36]:
arr[2:,1:]

array([[ 8,  9],
       [11, 12],
       [14, 15]])

In [37]:
arr[1:3,0:2]

array([[4, 5],
       [7, 8]])

In [54]:
arr = np.arange(0,10,2)

arr

array([0, 2, 4, 6, 8])

In [55]:
np.linspace(0,10,50) #Generates 50 numbers between 0 and 10

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [56]:
arr[2:] = 100

arr

array([  0,   2, 100, 100, 100])

In [7]:
arr1 = arr #arr1 is reference of arr, and they share same memory. Any operation we do on 1 array will impact another array.

arr1[2:] = 200 #This will also change values in arr array, as arr1 is a reference of arr

print(arr1)
print(arr)

[  1   2 200 200 200]
[  1   2 200 200 200]


In [8]:
arr1 = arr1.reshape(5,1) #Reshape would not be effective on arr as shape values might be saved differently for the 2 arrays

print(arr1)
print(arr)

[[  1]
 [  2]
 [200]
 [200]
 [200]]
[  1   2 200 200 200]


In [78]:
arr1[2,0] = 5

In [80]:
arr

array([  0,   2,   5, 200, 200])

In [86]:
arr1 = arr.copy() #This would create a different array with different memory location

arr1[2] = 10

print(arr1)
print(arr) # arr array is not updated

[  0   2  10 200 200]
[  0   2   5 200 200]


In [93]:
print(arr*2)

print(arr>100)

[  0   4  10 400 400]
[False False False  True  True]


In [94]:
np.arange(0,10).reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [106]:
np.ones(4,dtype=int)

np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [139]:
# Random Distribution

arr_rand = np.random.rand(3,4)

In [18]:
# Standard Normal Distribution
# mean=0, standard deviation=1
arr_randn = np.random.randn(3,4)

In [19]:
import seaborn as sns
import pandas as pd

In [21]:
sns.distplot(pd.DataFrame(arr_randn))

C:\Users\Ziyaad\AppData\Local\Temp\ipykernel_2572\3097506380.py:1: UserWarning: 

`distplot` is a deprecated function and will be removed in seaborn v0.14.0.

Please adapt your code to use either `displot` (a figure-level function with
similar flexibility) or `histplot` (an axes-level function for histograms).

For a guide to updating your code to use the new functions, please see
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751

  sns.distplot(pd.DataFrame(arr_randn))


<Axes: ylabel='Density'>

In [143]:
sns.distplot(pd.DataFrame(arr_randn))

C:\Users\Ziyaad\AppData\Local\Temp\ipykernel_54032\3097506380.py:1: UserWarning: 

`distplot` is a deprecated function and will be removed in seaborn v0.14.0.

Please adapt your code to use either `displot` (a figure-level function with
similar flexibility) or `histplot` (an axes-level function for histograms).

For a guide to updating your code to use the new functions, please see
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751

  sns.distplot(pd.DataFrame(arr_randn))


<Axes: ylabel='Density'>

In [144]:
np.random.randint(0,100,8) #Generate 8 int number between 0 to 100

array([92, 70, 82, 30, 48, 88, 23, 50])

In [148]:
np.random.random_sample((3,4))

array([[0.63914484, 0.66109168, 0.44484851, 0.0559851 ],
       [0.83414221, 0.21072684, 0.19527635, 0.65363565],
       [0.75299504, 0.32812573, 0.72933531, 0.96821194]])

Practice Questions

In [ ]:
# 1. Element-wise multiplication between 3D array a and 2D array b using broadcasting.
a = np.random.rand(2, 3, 4)
b = np.random.rand(3, 4)

result = a * b
print(result)


In [ ]:
#2. Perform element-wise operations (addition, subtraction, multiplication, and division) between two 2D arrays c and d using broadcasting.
def elementwise_operations(c, d):
    try:
        addition = c + d
        subtraction = c - d
        multiplication = c * d
        division = c / d
        return addition, subtraction, multiplication, division
    except ValueError:
        return "Broadcasting not possible with the given shapes."

c = np.random.rand(3, 4)
d = np.random.rand(3, 1)
add, sub, mul, div = elementwise_operations(c, d)
print(add, sub, mul, div)


In [ ]:
# 3. Compute the outer product of 2D array e and 1D array f using broadcasting.
e = np.random.rand(5, 3)
f = np.random.rand(5)
print(e,f)

outer_product = e[:, :, np.newaxis] * f[np.newaxis, :, np.newaxis]
print(outer_product)


In [ ]:
# 4. Extract every other element along the first and second dimensions of a 3D array g.

g = np.random.rand(4, 3, 2)

extracted = g[::2, ::2, :]
print(extracted)

In [ ]:
# 5. Function that returns a new array where each element is the sum of the elements along the diagonal specified by row indices i and column indices j.
def diagonal_sum(h, i, j):
    k = np.array([h[row, col] for row, col in zip(i, j)])
    return k

# Example usage
h = np.random.rand(5, 5)
i = np.array([0, 1, 2, 3, 4])
j = np.array([0, 1, 2, 3, 4])
k = diagonal_sum(h, i, j)
print(k)


In [ ]:
# 6. Function that returns a new array where each element is the product of the corresponding row and column means in a 2D array l.
def row_col_mean_product(l):
    row_means = l.mean(axis=1)
    col_means = l.mean(axis=0)
    result = np.outer(row_means, col_means)
    return result

# Example usage
l = np.random.rand(4, 5)
m = row_col_mean_product(l)
print(m)


In [ ]:
# 7. Reshape a 2D array n into a 3D array and then flatten it back to 2D.
# Given array
n = np.random.rand(4, 6)

# Reshape to (2, 2, 6)
reshaped = n.reshape(2, 2, 6)

# Flatten back to (4, 6)
flattened = reshaped.reshape(4, 6)
print(flattened)


In [ ]:
# 8. Function that rolls a 2D array o along the first axis by a specified number of positions.
def roll_array(o, num_positions):
    rolled = np.roll(o, num_positions, axis=0)
    return rolled

# Example usage
o = np.array([[1, 2, 3], [4, 5, 6]])
rolled = roll_array(o, 1)
print(rolled)


In [ ]:
# 9. Function that replaces all occurrences of a specified value x with the mean of the neighboring elements in a 2D array p.
def replace_with_neighbor_mean(p, x):
    p = np.array(p, dtype=float)  # Ensure it's float to handle NaN
    mask = (p == x)
    padded = np.pad(p, pad_width=1, mode='constant', constant_values=np.nan)
    
    for (i, j) in np.argwhere(mask):
        neighbors = padded[i:i+3, j:j+3]
        p[i, j] = np.nanmean(neighbors)
    
    return p

# Example usage
p = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = 5
replaced = replace_with_neighbor_mean(p, x)
print(replaced)
